% Decide wich circuit to compare (enable=1) 

bus_24mols_enable = 1;
buslargo_24mols_enable = 1;
connection_L_enable = 1;
connection_Lcorr_enable = 1;
connection_Llarge_enable = 1;
connection_T_enable = 1;
connection_Tcorr_enable = 1;
connection_Tlarge_enable = 1;
crosstalk_enable = 1;
fanout_enable = 1;
fanout_large_enable = 1;
fulladder_enable = 1;
inverter_enable = 1;
inverter_large_enable = 1;
majority_voter_enable = 1;
majority_voter_large_enable = 1;
majority_voter_unbalance_enable = 1;
majority_voter_unbalance2_enable = 1;
wire_8mols_1nm_enable = 1;
wire_8mols_08nm_enable = 1;
wire_8mols_12nm_enable = 1;
wire_16mols_1nm_enable = 1;
wire_16mols_08nm_enable = 1;
wire_16mols_12nm_enable = 1;
wire_24mols_clocked_enable = 1;
